# Introducción al modelado

### Problemas de negocio
Pero ya tienen soluciones a sus negocios.

   * Panadero: Predecir demanda de pan.
   * Operario de fábrica: Cada 3 meses mira que cada máquina funcione bien.
   * Especialista de marketing: Mailing list, siempre usa la misma.
   * Radiólogo: Buscar un cuerpo extraño en la radiografía.

No han aplicado las innovaciones: Cloud, Machine learning, IoT y sensors, Data.
   * Cloud: Pagas por uso del cloud, la mejor máquina que haya disponible.
   * Data: Generamos muchísimos datos, ya sea en lo personal o en empresa. Administraciones públicas con portales de datos.
   * Machine learning: ML5pose. Le das una imagen y te dice la pose de esa persona.

Hay una gran diferencia entre las soluciones de negocio tradicionales a las nuevas oportunidades de las innovaciones.

### Machine learning
Técnicas de computación que usa estadística para habilitar los sistemas de computación la habilidad de "aprender" con datos, modelos.

Automatizar toda la cadena de producción. Desventaja: Peor calidad delproducto. AKA Toyota. Lo ideal, que tareas automatizar y cuales no.

Cognitive tasks, automated with machine learning. Automatizar tareas cognitivas sencillas. Tipos de aprendizaje (99,9% generalización/relación y comparación):

   * Generalización y relación: Circulo relleno V, cuadrado vacío X, triángulo relleno X, circulo vacío V. ¿Qué entra? Según características, target y relación de lo que ha entrado, llegamos a la conclusión de que lo que entra es el círculo. Y generaliza a que todas las figuras con forma de círculo, entran. F(características) = target.
   
   * Comparación: Extraemos características (círtricos, colores, formas, acidez, origen, hoja). Distancia entre las características (d1, d2). Grupo segmento.
   
   * Refuerzo: Se basa por la recompensa. Va a intentar varias acciones, hasta que consiga la recompensa.

### ¿Qué tipos de tareas cognitivas?:

   * Supervised learning: En el supervisado tienes etiquetas. Problemas: Hay que etiquetar continuamente la info. Aprende por elementos pasados:
       * Regression: Predice el número.
       * Clasificación de etiquetas, predice etiquetas.
   
   * Semi-supervisado: Hay un etiquetado parcial y el resto por comparación. Aprende por comparación:
       * Clustering: Encuentra los elementos distintos.
       * Reducción de dimensionalidad: Explica los elementos sin tantos atributos
   
   * Unsupervised learning: No etiqueto los elementos, lo hago por comparaciones.
   
   
* Machine Learning VS AI: AI usa el ML para explicar como los humanos piensan.

* ML vs Deep Learning: Es un tipo de ML learning model.

* Ml vs Statistics: ALgunos aspectos de la estadística se aplica y se renombra como machine learning

### Machine Learning example: Prediciendo precios de casas

Problema: Precio de la casa según las características.

Solución: De precios de casa extraemos las características. Extraemos datos. Categorizamos las características. Cada línea representa una casa. Entre una etiqueta/target, establecer una correlación.

Correlación es un término de estadística. Está muy ligada a las regresiones lineales. No es el único criterio para saber si una variable es buena o no.

¿Que características o variables habrá que coger?
El saber hacer de Data Science es necesario un knowledge expertise bueno, para elegir bien una buena relación entre target y cracterísticas. Es necesario elegir bien las características que mejoren el modelo de predicción. Añadir cuantas más características que mejoren el modelo.

#### Modelo: Simplificación de la realidad.

   * Example of model 1: Regresión lineal. Intenta enontrar una función lineal. Necesitamos encontrar a,b,c y d que tengan una mejor relación.
   
   * Example of model 2: Decision tree. Un arbol de decisión trata de encontrar un path para explicar el target. Divdimos casos entre varias características. Necesitamos encontrar los mejores splits para nuestros modelos.
   
   * Randomon Forest, K-neighbors, SVM, Neural Networks, Deep Learning y la lista de modelos crece.
   
Deep Learning, como lo hace: Los pcs son gilipollas, no tienen esa capacidad de abstracción para la regresión lineal. Quiero guardar el millón de puntos. No simplificamos con matemáticas, nos quedamos con todos los datos, incluso aquellos que aparentemente no tienen relación.

### Parámetros del modelo

El Data Scientist trabaja para encontrar los mejores parámetros del modelo.

Parámetros, que peso de decisión le doy a una características. Lo hace automáticamente el algoritmo, que es quien encuentra los parámetros y le da el peso. Con las estadística podemos modelizar la incertidumbre.

¿Cómo encuentras los mejores parámetros?

Training: Cada modelo tiene un particular way para encontrar los mejores parámetros.

Hay muchas métricas que pueden ser elegidas para una tarea:

   * Bias: Media de los errores.
   * MAE: MEdia del valor absoluto de los errores.
   * RMSE:  La media del cuadrado de los errores.
   * Hay más...
   
Elegimos los parametros del modelo que nos dan la mejor métrica. Elegiremos el modelo que tenga menor media de errores. El negocio o la necesidad de negocio, estableceremos las métricas que más se ajusten a nuestras necesidades para elegir el modelo.

FE: Cogemos las características disponibles en tabla y dividimos en 2 el set:

   * 1 set para calcular los parámetros: Training set. (Es como el 80-90%)
   * 1 set para calcular las métricas: Test set.
   
Modelo final. Hacemos un ranking de modelos.

Model usage.

SalePrice = F(Hose features)

### Machine learning is about features, models and metrics

   * 
   * 
   * 

### Clasificación

Regresión logística.

### Segmentation

No tengo etiquetas. Detectar grupos similares de elementos.
Solo tengo características. Encontramos grupos de clientes similares por su proximidad.

## Trasladar el Machine Learning a los problemas de negocio

   * Panadero: Predecir harina tiene que comprar. ¿Predecimos harina o número de clientes? como DS tenemos que elegir que predecir: Nos quedamos con clientes. Si queremos predecir un número, se ha de elegir un modelo de regresión.
   
   * Operario de la fábrica: Predecir dentro de cuanto tiempo fallará la máquina. ¿Fallará mañana, cuanto tiempo, fallará o no? Elegiremos el modelo de clasificación.
   
   * Marketing: Segementación de clientes: Segmentar su problema en distintos grupos y luego aplicamos distintos a cada grupo. Conversión, clasificación.
   
   * Médico, predecir con las radiografías. Clasificación.

Cualquier problema de negocio puede ser analizado por los siguientes pasos:

   1) Business Value and Measure of Success(1)
   
   2) Data Sources(2)
   
   3) Machine Learning tasks + Metric(3)
   
   4) Features Extraction + Model Creation(4)
   
   5) Industrialization and Maintenance (5)
   
### CANVAS de Machine Learning.

Colaboración con Data Scientist. Discutir sobre los datos: Fuentes de datos, histórico, Características, frecuencia, vlor de éxito...

   * Extraction of feature (2)
   
   * selection of ML task and evaluation (3)
   
   * Model Creation (4)
   
   * Quantity of Data > Parameters
   
   * Loop until satisfied

Si el modelo de todos, no es bueno. Solución: 1) Más datos. 2) Nuevas y más características. 3)Ver si hay estadísticas que emporan los datos (Se ponen a probar a cambiar columnas de sitios y probar como empeora o mejora el modelo) 4) Probar nuevos modelos.

Los deep learning están prohibidos. Los modelos de machine learning han de ser explicados en auditorías. Podemos hacer modelos de deep learning y luego sobre esos segmentos hacemos un modelo de regresión lineal o logística. Hacemos un modelo sobre otro. Se recomienda que las variables estén correladas unas entre otras.

gdpr: No se pueden almacenar datos no útiles. ¿Pero como decides que dato es útil o no?

## Activity 1: Define your business (10min)

#### Steps:
   1) List business that are related to the defined problem:
       * 1. Organismos públicos
       * 2. Empresas de movilidad
       * 3. Empresas de energía
       * 4. Empresas de parking
       * 5. Empresas de marketing verde, deportivo.
       * 6. Turismo rural
       * 7. Turismo ecosostenible
       * 8. Farmaceuticas
       * 9. Empresa de ventas de mascarillas
       * 10.

   2) Choose 1 business
       Empresa de venta de mascarillas.
       
### Negocio: Empresa de venta de mascarillas.

## Activity 2: Problema de negocio (10min)

   * No hay mercado, hay que crearlo.
   * Prejuicios.
   * Estética del producto.
   * Foco: Las grandes ciudades de España.
   * Vender la necesidad del produto al usuario.
   * Encontrar nuevas oportunidades de negocio fuera de la estacionalidad del producto.
   * Problema de distribución.
   * Zonas. Hay algunas zonas en las que se ponen y otras en las que no. Zonas verdes por ejemplo no.
   * Mascarillas de hospital. Sustituto barato o gratuito. No son mascarillas con filtros.
       
## Activity 3: Business sucess (10min)
Definir KPIs or milestones.

   * Dónde y cuando. Número de gente que coge/compra la mascarilla.
   * Volumen de ventas. Unidades.
   * Posicionamiento de producto: Encuestas.
       * Gente que lo conoce
       * Gente que lo usa
       * Gente que lo compra
   * Interés en el producto: Clicks.

In [20]:
import pandas as pd
datos_18 = pd.read_csv('./madrid_2018.csv', sep = ',', nrows = 100000)

In [16]:
pd.options.display.max_columns = None
datos_18.sample(10)

,date,BEN,CH4,CO,EBE,NMHC,NO,NO_2,NOx,O_3,PM10,PM25,SO_2,TCH,TOL,station
53060,2018-01-04 04:00:00,NaN,NaN,0.4,NaN,NaN,33.0,48.0,98.0,NaN,2.0,NaN,6.0,NaN,NaN,28079057
60018,2018-01-16 06:00:00,0.6,1.49,NaN,0.8,0.07,53.0,62.0,143.0,NaN,15.0,NaN,NaN,1.56,2.8,28079055
3195,2018-03-06 14:00:00,NaN,NaN,0.4,NaN,NaN,9.0,33.0,47.0,53.0,NaN,NaN,NaN,NaN,NaN,28079016
27828,2018-04-18 08:00:00,NaN,NaN,0.3,NaN,NaN,17.0,50.0,76.0,NaN,18.0,NaN,10.0,NaN,NaN,28079057
34033,2018-04-29 04:00:00,0.2,1.37,0.2,0.1,0.02,5.0,25.0,32.0,71.0,6.0,3.0,1.0,1.38,0.4,28079008
2605,2018-03-05 13:00:00,NaN,NaN,NaN,NaN,NaN,3.0,25.0,30.0,NaN,3.0,2.0,NaN,NaN,NaN,28079047
20649,2018-04-05 21:00:00,NaN,NaN,0.5,NaN,NaN,22.0,67.0,101.0,NaN,17.0,NaN,12.0,NaN,NaN,28079036
3251,2018-03-06 16:00:00,NaN,NaN,0.3,NaN,NaN,9.0,27.0,41.0,65.0,NaN,NaN,NaN,NaN,NaN,28079039
23296,2018-04-10 11:00:00,NaN,NaN,NaN,NaN,NaN,35.0,62.0,114.0,NaN,10.0,9.0,NaN,NaN,NaN,28079050
44955,2018-02-18 03:00:00,NaN,NaN,0.3,NaN,NaN,1.0,14.0,16.0,59.0,NaN,NaN,NaN,NaN,NaN,28079016

In [17]:
list(datos_18.columns)

['date',
 'BEN',
 'CH4',
 'CO',
 'EBE',
 'NMHC',
 'NO',
 'NO_2',
 'NOx',
 'O_3',
 'PM10',
 'PM25',
 'SO_2',
 'TCH',
 'TOL',
 'station']

In [21]:
datos_18 = datos_18[['date','NO_2','station']]
datos_18.head(5)

                  date  NO_2   station
0  2018-03-01 01:00:00  29.0  28079004
1  2018-03-01 01:00:00  40.0  28079008
2  2018-03-01 01:00:00  41.0  28079011
3  2018-03-01 01:00:00  35.0  28079016
4  2018-03-01 01:00:00  27.0  28079017

In [22]:
datos_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69096 entries, 0 to 69095
Data columns (total 3 columns):
date       69096 non-null object
NO_2       68826 non-null float64
station    69096 non-null int64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.6+ MB